from tools.handlers import get_app_status, get_current_date, get_current_time
from tools.calculator import calculate
from tools.web_search import web_search
from tools.filesystem import read_file, list_directory

try:
    from tools.Github.handlers import (
        add_labels_to_issue,
        create_branch,
        create_issue,
        create_or_update_file,
        create_pull_request,
        get_commits,
        get_file_contents,
        get_issue,
        get_pull_request,
        get_rate_limit,
        get_repo_details,
        list_branches,
        list_labels,
        list_pull_requests,
        list_repo_issues,
        list_repositories,
        search_issues,
        search_repositories,
        sync_issue_to_task,
        sync_task_to_issue,
        update_issue,
    )
except ModuleNotFoundError:  # pragma: no cover - fallback for non-package execution
    from Github.handlers import (
        add_labels_to_issue,
        create_branch,
        create_issue,
        create_or_update_file,
        create_pull_request,
        get_commits,
        get_file_contents,
        get_issue,
        get_pull_request,
        get_rate_limit,
        get_repo_details,
        list_branches,
        list_labels,
        list_pull_requests,
        list_repo_issues,
        list_repositories,
        search_issues,
        search_repositories,
        sync_issue_to_task,
        sync_task_to_issue,
        update_issue,
    )

TOOL_REGISTRY = {
    "get_current_time": get_current_time,
    "get_current_date": get_current_date,
    "get_app_status": get_app_status,
    "calculate": calculate,
    "web_search": web_search,
    "read_file": read_file,
    "list_directory": list_directory,
    "list_repo_issues": list_repo_issues,
    "list_repositories": list_repositories,
    "get_repo_details": get_repo_details,
    "search_repositories": search_repositories,
    "get_issue": get_issue,
    "create_issue": create_issue,
    "update_issue": update_issue,
    "search_issues": search_issues,
    "list_pull_requests": list_pull_requests,
    "get_pull_request": get_pull_request,
    "create_pull_request": create_pull_request,
    "list_branches": list_branches,
    "get_commits": get_commits,
    "create_branch": create_branch,
    "get_file_contents": get_file_contents,
    "create_or_update_file": create_or_update_file,
    "list_labels": list_labels,
    "add_labels_to_issue": add_labels_to_issue,
    "get_rate_limit": get_rate_limit,
    "sync_task_to_issue": sync_task_to_issue,
    "sync_issue_to_task": sync_issue_to_task,
}